---
- hosts: all
  sudo: true
  tasks:

    # install update cache
    - name: update apt cache
      apt: update_cache=yes

    # install packages
    - name: Install list of packages
      apt: pkg={{item}} state=installed
      with_items:
        - build-essential
        - g++
        - flex
        - bison
        - gperf
        - ruby
        - perl
        - libsqlite3-dev
        - libfontconfig1-dev
        - libicu-dev
        - libfreetype6
        - libssl-dev
        - libpng-dev
        - libjpeg-dev
        - python
        - libx11-dev
        - libxext-dev
        - git

    # checkout and compile phantomjs
    - git: repo=https://github.com/ariya/phantomjs.git dest=/home/vagrant/phantomjs_2.0.0 recursive=yes version=2.0.0 accept_hostkey=true
    - command: rm -f /home/vagrant/phantomjs_2.0.0/bin/phantomjs
    - shell: echo "y" | sudo ./build.sh chdir=/home/vagrant/phantomjs_2.0.0
      async: 3600
      poll: 0
      register: phantomjs_build
    - wait_for: path=/home/vagrant/phantomjs_2.0.0/bin/phantomjs delay=10 timeout=3600
    - command: rm -rf /vagrant/build
    - file: path=/vagrant/build state=directory mode=0755
    - command: mv /home/vagrant/phantomjs_2.0.0/bin/phantomjs /vagrant/build/phantomjs
